mod attributes;
mod element;
mod styles;

pub use attributes::Attribute;
pub use attributes::Charset;
pub use attributes::CharsetValue;
pub use attributes::Lang;
pub use attributes::LanguageSubTag;
pub use attributes::LanguageTag;
pub use attributes::StyleAttr;
pub use element::render_simple_html_page;
pub use element::AsTagRenderable;
pub use element::Body;
pub use element::Code;
pub use element::Element;
pub use element::GenericElement;
pub use element::Head;
pub use element::Html;
pub use element::Meta;
pub use element::Pre;
pub use element::Renderable;
pub use element::Table;
pub use element::TagRenderable;
pub use element::Tbody;
pub use element::Td;
pub use element::Th;
pub use element::Thead;
pub use element::Thr;
pub use element::Tr;
pub use element::H1;
pub use element::P;
pub use styles::Margin;
pub use styles::MaxWidth;
pub use styles::Style;
